/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stoplimit1;

import java.awt.AWTException;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author YOUCEF
 */
public class StopLimitFrame extends javax.swing.JFrame {

    /**
     * Creates new form StopLimitFrame
     */
    public StopLimitFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        BrowserName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtCoinSymbole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtPriceOfBuy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtPercentage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtNowPrice = new javax.swing.JTextField();
        TxtTradeWith = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("RUN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BrowserName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "google" }));
        BrowserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowserNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Browser");

        jLabel2.setText("Trade With");

        jLabel3.setText("Coin Symbole");

        TxtCoinSymbole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCoinSymboleActionPerformed(evt);
            }
        });

        jLabel4.setText("Price Of Buy");

        jLabel5.setText("percentage %");

        TxtPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPercentageActionPerformed(evt);
            }
        });

        jLabel6.setText("Now Price");

        TxtNowPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNowPriceActionPerformed(evt);
            }
        });

        TxtTradeWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTradeWithActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtNowPrice)
                    .addComponent(TxtPercentage)
                    .addComponent(TxtCoinSymbole)
                    .addComponent(TxtPriceOfBuy)
                    .addComponent(BrowserName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTradeWith)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BrowserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtTradeWith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtCoinSymbole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtPriceOfBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6))
                    .addComponent(TxtNowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        CoinRobot c;
        try {
            go g = new go();
            g.add(
                    TxtCoinSymbole.getText(),
                    Float.parseFloat(TxtPriceOfBuy.getText()),
                    Float.parseFloat(TxtNowPrice.getText()) - (Float.parseFloat(TxtNowPrice.getText()) * Float.parseFloat(TxtPercentage.getText()) / 100),
                    Float.parseFloat(TxtNowPrice.getText()),
                    TxtTradeWith.getText(),
                    Float.parseFloat(TxtPercentage.getText())
            );
            c = new CoinRobot();
            c.oneLeftClickWithMouse(975, 455);// close the secend proram
            c.oneLeftClickWithMouse(290, 870);// open the browser
            c.wait(50);
            c.oneLeftClickWithMouse(340, 507); // take ex for the price 
            c.wait(150);
            c.MouseMove(668, 600);
            c.wait(50);
            c.HoldMouse();
            c.MouseMove(607, 600);
            c.wait(50);
            c.LetHoldMouse();
            c.wait(50);
            c.PressCopy();//copy the price
            c.wait(50);
            c.oneLeftClickWithMouse(1506, 12);//hide the brwoser
            c.wait(50);
            c.oneLeftClickWithMouse(320, 800);// open the secend program
            c.wait(50);
            c.pressKeybord(KeyEvent.VK_ENTER);// open the secend program
            c.wait(150);
            c.oneLeftClickWithMouse(800, 412); // put the number in the fiald
            c.wait(50);
            c.PressPaste();
            c.wait(50);
            c.oneLeftClickWithMouse(650, 450);// run the program

        } catch (AWTException ex) {
            System.out.println("problem here");
        }

        /*CoinRobot c;

        try {
            go g = new go();
            g.add(
                    TxtCoinSymbole.getText(),
                    Float.parseFloat(TxtPriceOfBuy.getText()),
                    Float.parseFloat(TxtNowPrice.getText()) - (Float.parseFloat(TxtNowPrice.getText()) * Float.parseFloat(TxtPercentage.getText()) / 100),
                    Float.parseFloat(TxtNowPrice.getText()),
                    TxtTradeWith.getText(),
                    Float.parseFloat(TxtPercentage.getText())
            );
            c = new CoinRobot();
            c.oneLeftClickWithMouse(975, 455);
            c.oneLeftClickWithMouse(290, 870);
            c.wait(100);
            c.oneLeftClickWithMouse(400, 500);
            c.wait(100);
            c.MouseMove(668, 600);
            c.wait(100);
            c.HoldMouse();
            c.MouseMove(617, 600);
            c.wait(100);
            c.LetHoldMouse();
            c.PressCopy();
            c.oneLeftClickWithMouse(30, 880);
            c.wait(100);
            c.Typing("kklnukjadqola.java");// secend program
            c.wait(500);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_ENTER);
            c.wait(500);
            c.oneLeftClickWithMouse(800, 412);
            c.PressPaste();
            c.oneLeftClickWithMouse(650, 450);

        } catch (AWTException ex) {
            System.out.println("problem here");
        }*/
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtCoinSymboleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCoinSymboleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCoinSymboleActionPerformed

    private void BrowserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrowserNameActionPerformed

    private void TxtPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPercentageActionPerformed

    }//GEN-LAST:event_TxtPercentageActionPerformed

    private void TxtNowPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNowPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNowPriceActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        go g = new go();

        TxtNowPrice.setText(g.Get("NOW_PRICE"));
        TxtPriceOfBuy.setText(g.Get("PRICE_OF_BUY"));
        TxtCoinSymbole.setText(g.Get("COIN_SYMBOLE"));
        TxtPercentage.setText(g.Get("PERRCENTAGE"));
        TxtTradeWith.setText(g.Get("TRAED_WITH"));

    }//GEN-LAST:event_formWindowOpened

    private void TxtTradeWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTradeWithActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTradeWithActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    go g = new go();
    g.delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StopLimitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BrowserName;
    private javax.swing.JTextField TxtCoinSymbole;
    private javax.swing.JTextField TxtNowPrice;
    private javax.swing.JTextField TxtPercentage;
    private javax.swing.JTextField TxtPriceOfBuy;
    private javax.swing.JTextField TxtTradeWith;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
